server:
  port: 8201

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy?serverTimezone=GMT%2b8
    username: root
    password: DXH

  application:
    name: borrowservice

  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        ephemeral: false
        cluster-name: Chengdu
        # 权重大小，越大越优先调用，默认为1
        weight: 0.5