server:
  port: 8201

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudstudy?serverTimezone=GMT%2b8
    username: root
    password: DXH

  application:
    name: borrowservice

  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        namespace: 07206191-55ba-4789-8f57-a3a034de9361
        ephemeral: false
        cluster-name: Chengdu
        # 权重大小，越大越优先调用，默认为1
        weight: 0.5
    loadbalancer:
      nacos:
        enabled: true

    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
      web-context-unify: false
      # 将刚刚编写的请求映射设定为限流页面
      block-page: /blocked
