server:
  port: 8301

spring:
  # datasource 在 nacos 中配置


  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: localhost:8848
        namespace: 07206191-55ba-4789-8f57-a3a034de9361
